name: community_marketplace
description: A cross-platform community-driven marketplace app for buying, selling, and delivering items.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  get_it: ^7.6.4
  equatable: ^2.0.5

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # HTTP & API
  dio: ^5.3.2
  retrofit: ^4.0.3

  # UI & Navigation
  go_router: ^12.1.1
  cached_network_image: ^3.3.0

  # Authentication
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6

  # Notifications
  firebase_messaging: ^14.7.9

  # Location
  geolocator: ^10.1.0

  # Image handling
  image_picker: ^1.0.4

  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  retrofit_generator: ^7.0.8
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  # fonts:
    # - family: NotoSansArabic
    #   fonts:
    #     - asset: assets/fonts/NotoSansArabic-Regular.ttf
    #     - asset: assets/fonts/NotoSansArabic-Bold.ttf
    #       weight: 700
    # - family: Roboto
    #   fonts:
    #     - asset: assets/fonts/Roboto-Regular.ttf
    #     - asset: assets/fonts/Roboto-Bold.ttf
    #       weight: 700